org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.240
# The loader version range can only use the major version of FML as bounds
loader_version_range=[1,)

mod_id=bulk_cell_tweaks
mod_name=Bulk-Cell-Tweaks
mod_license=All Rights Reserved
mod_version=1.0.2
mod_group_id=com.zhichaoxi.bulk_cell_tweaks
